---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
```

# petroOne

The goal of petroOne is to ...

## Installation

You can install petroOne from github with:

```{r gh-installation, eval = FALSE}
# install.packages("devtools")
devtools::install_github("f0nzie/petroOne")
```

## Examples

### Get the number of papers for *neural networks*.

```{r example}

my_url <- make_search_url(query = "neural network", how = "any")
my_url
get_papers_count(my_url)
# 3284
```

### Read papers from from_year to to_year

```{r}
# neural network papers from 1990 to 2000. Exact phrase
my_url <- make_search_url(query = "neural network", 
                          from_year = 1990, 
                          to_year   = 2000, 
                          how = "all")
get_papers_count(my_url)
# 510
```

```{r}
library(petroOne)

my_url <- make_search_url(query = "neural network", 
                          from_year = 1990, 
                          to_year   = 1999, 
                          how = "all")

get_papers_count(my_url)
# 415
onepetro_page_to_dataframe(my_url)
```

### Get papers by document type (dc_type)

```{r}
# specify document type = "conference-paper", rows = 1000

my_url <- make_search_url(query = "neural network", 
                          how = "all",
                          dc_type = "conference-paper",
                          rows = 1000)

get_papers_count(my_url)
# 2661
onepetro_page_to_dataframe(my_url)
```



```{r}
# specify document type = "journal-paper", rows = 1000

my_url <- make_search_url(query = "neural network", 
                          how = "all",
                          dc_type = "journal-paper",
                          rows = 1000)

get_papers_count(my_url)
# 303
onepetro_page_to_dataframe(my_url)
```



```{r}
library(petroOne)

my_url <- make_search_url(query = "neural network", 
                          how = "all")

result <- read_onepetro(my_url)
raw_right <- publication_result_right(result)
raw_left  <- publication_result_left(result)

summary_by_doctype(raw_right)
summary_by_publisher(raw_right)

summary_by_dates(raw_left)
summary_by_publications(raw_left)
```

