---
title: "R Notebook"
output: html_notebook
---

```{r}
# read folder ./inst/extdata
# detect files ending .txt and put them in a vector or list
# read text file
    # read first line and put it as a discipline
    # read next lines (subjects) as rows and put them in a dataframe
    # variable1: subject; variable2: discipline
    # remove blank rows
    # keep the dataframe
# move to next file
# save dataframe as RDA file in ./data
```



```{r}
# data files (.txt) are under `extdata`
extdata <- system.file("extdata", package = "petroOne")
extdata
```

```{r}
# list text files
pat <- ".txt"
label_files <- list.files(path = extdata, pattern = pat, full.names = TRUE)
label_files
```

```{r}
discipline <- lapply(label_files, function(x) readLines(x, n = 1))
discipline
```

```{r}
cumdf <- data.frame()
for (i in seq_len(length(discipline))) {
    df <- read.table(label_files[i], header=F, sep = "\n")
    df$V2 <- discipline[[i]]
    cumdf <- rbind(cumdf, df)
}
names(cumdf) <- c("subject", "discipline")
cumdf
```


```{r}
# read label files, one row at a time
datalist = lapply(label_files, function(x) read.table(x, header=F, sep = "\n")) 
datafr = do.call("rbind", datalist) 
datafr
```



```{r}
utils::read.table(data_file, header = TRUE)
```


