---
title: "R Notebook"
output: html_notebook
---

```{r}
library(petroOne)

# 1 - 1000 rows
# start: blank

# search for neural network has returned 2,918 results. 
url <- "https://www.onepetro.org/search?q=neural+network&peer_reviewed=&published_between=&from_year=&to_year=&rows=1000&dc_type=conference-paper"

webpage1 <- xml2::read_html(url)
xml2::write_html(webpage1, file = "1000_conference.html")
onepetro_page_to_dataframe("1000_conference.html")
```

```{r}
# 1000 - 2000
# start: 1000
# rows:  1000
# 
url <- "https://www.onepetro.org/search?start=1000&q=neural+network&peer_reviewed=&published_between=&from_year=&to_year=&rows=1000&dc_type=conference-paper"

webpage1 <- xml2::read_html(url)
xml2::write_html(webpage1, file = "2000_conference.html")
onepetro_page_to_dataframe("2000_conference.html")
```


```{r}
# 2000 - 3000
# start: 2000
# rows:  1000
# 
url <- "https://www.onepetro.org/search?start=2000&q=neural+network&peer_reviewed=&published_between=&from_year=&to_year=&rows=1000&dc_type=conference-paper"

webpage1 <- xml2::read_html(url)
xml2::write_html(webpage1, file = "3000_conference.html")
onepetro_page_to_dataframe("3000_conference.html")
```



```{r}
library(petroOne)

p1 <- onepetro_page_to_dataframe("1000_conference.html")
p2 <- onepetro_page_to_dataframe("2000_conference.html")
p3 <- onepetro_page_to_dataframe("3000_conference.html")

nn_papers <- rbind(p1, p2, p3)
nn_papers

```
